export interface CustomizationOption {
  label: string
  choices: string[]
}

export interface Product {
  id: string
  name: string
  price: number
  description: string
  image: string
  category: string
  customizations: CustomizationOption[]
}

export interface CartItem {
  product: Product
  quantity: number
  selectedOptions: Record<string, string>
}

export interface Order {
  // identifier generated by the frontend (ORD-...) and stored in Mongo as well
  id: string
  // MongoDB document id (optional when returned from database)
  _id?: string
  customerId: string
  customerName: string
  customerEmail: string
  shippingAddress: string
  items: CartItem[]
  totalAmount: number
  transactionId: string
  paymentMethod: string
  // new field indicates whether a UPI payment has been approved by admin
  paymentApproved: boolean
  status: "Pending" | "Processing" | "Shipped" | "Delivered"
  date: string
}

export interface User {
  id: string
  name: string
  email: string
  role: "user" | "admin" | "super-admin"
}

export const products: Product[] = [
  {
    id: "planner-1",
    name: "Daily Productivity Planner",
    price: 599,
    description:
      "Maximize your daily output with structured time blocks, priority lists, and gratitude journaling sections.\n\nCrafted for peak performers, this planner divides your day into clear, actionable segments. It features hourly un-dated schedules, space for top-three daily priorities to maintain focus, and end-of-day reflection prompts to ensure you're always growing.\n\nFeatures:\n• 180 pages of premium 100gsm bleed-resistant paper\n• Lay-flat binding for easy writing\n• Built-in ribbon marker and elastic closure\n• Perfect for entrepreneurs, students, and busy professionals.",
    image: "/images/planner-1.jpg",
    category: "Daily",
    customizations: [
      { label: "Size", choices: ["A5", "A4", "B5"] },
      { label: "Cover Style", choices: ["Hardcover", "Softcover", "Spiral"] },
      { label: "Page Layout", choices: ["Lined", "Dotted", "Grid", "Blank"] },
    ],
  },
  {
    id: "planner-2",
    name: "Weekly Habit Tracker",
    price: 449,
    description:
      "Build lasting habits with weekly tracking spreads, reflection prompts, and progress charts.\n\nStop breaking the chain! This weekly tracker allows you to visualize your physical, mental, and professional habits across a 52-week spread. The minimalist design removes distractions, leaving only your goals in focus.\n\nFeatures:\n• 52 undated weekly spreads\n• Dedicated habit grid for up to 10 daily habits\n• Beige linen cover that looks elegant on any desk\n• Specialized monthly review pages to analyze your routine.",
    image: "/images/planner-2.jpg",
    category: "Weekly",
    customizations: [
      { label: "Size", choices: ["A5", "A4"] },
      { label: "Cover Style", choices: ["Linen", "Hardcover", "Softcover"] },
      { label: "Page Layout", choices: ["Pre-printed", "Dotted", "Grid"] },
    ],
  },
  {
    id: "planner-3",
    name: "Student Study Planner",
    price: 349,
    description:
      "Stay on top of assignments, exams, and projects with dedicated study schedules and subject trackers.\n\nDesigned specifically for academic success, this planner helps students juggle multiple classes with ease. It includes semester overview maps, grade trackers, and assignment deadline calendars so nothing slips through the cracks.\n\nFeatures:\n• Dual-semester layout mapping\n• Color-coded sticker sheet included\n• Lightweight design for easy backpack carrying\n• Inspirational quotes to combat mid-semester burnout.",
    image: "/images/planner-3.jpg",
    category: "Academic",
    customizations: [
      { label: "Size", choices: ["A5", "B5"] },
      { label: "Cover Style", choices: ["Softcover", "Spiral", "Hardcover"] },
      { label: "Page Layout", choices: ["Lined", "Grid", "Mixed"] },
    ],
  },
  {
    id: "planner-4",
    name: "Minimalist Undated Planner",
    price: 299,
    description:
      "Start anytime with this clean, undated planner. Simple layouts let you customize your planning system your way.\n\nNo more wasted pages. If you skip a day or a week, simply pick up right where you left off. The dot grid and subtle lines offer a framework without forcing you into a specific scheduling methodology. Perfect for bullet journalers and free-thinkers.\n\nFeatures:\n• 100% undated flexible pages\n• Eco-friendly recycled paper materials\n• Subtle 5mm dot grid matrix pattern\n• Expandable inner pocket for loose receipts or notes.",
    image: "/images/planner-4.jpg",
    category: "Undated",
    customizations: [
      { label: "Size", choices: ["A5", "A6", "A4"] },
      { label: "Cover Style", choices: ["Hardcover", "Softcover"] },
      { label: "Page Layout", choices: ["Blank", "Dotted", "Lined"] },
    ],
  },
  {
    id: "planner-5",
    name: "Goal-Setting Vision Planner",
    price: 999,
    description:
      "Map your dreams into actionable goals with vision boards, quarterly reviews, and milestone trackers.\n\nTurn vague aspirations into concrete realities. This premium planner walks you through a step-by-step goal defining process, helping you reverse-engineer a 5-year vision down to what you should be doing today. It's half workbook, half daily planner.\n\nFeatures:\n• Guided vision board and core-values exercises\n• 90-day milestone checkpoints\n• Executive-tier dark green leather cover with gold foil embossing\n• Heavyweight 120gsm paper built for fountain pens.",
    image: "/images/planner-5.jpg",
    category: "Goals",
    customizations: [
      { label: "Size", choices: ["A4", "A5"] },
      { label: "Cover Style", choices: ["Hardcover", "Premium Leather"] },
      { label: "Page Layout", choices: ["Structured", "Dotted", "Mixed"] },
    ],
  },
]
